apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-deployment
spec:
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      containers:
      - name: blockchain
        image: blockchain
        imagePullPolicy: Never
        env:
          - name: MARIADB_HOST
            value: blockchain-database-service
          - name: RABBITMQ_HOST 
            value: rabbitmq-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
