apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-database-deployment
spec:
  selector:
    matchLabels:
      app: blockchain-database
  template:
    metadata:
      labels:
        app: blockchain-database
    spec:
      containers:
      - name: blockchain-database
        image: blockchain-database
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
