apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner-deployment
spec:
  selector:
    matchLabels:
      app: miner
  replicas: 2
  template:
    metadata:
      labels:
        app: miner
    spec:
      containers:
      - name: miner
        image: miner
        imagePullPolicy: Never
        env:
          - name: BLOCKCHAIN_SERVICE
            value: http://blockchain-service:5000/blockchain
          - name: RABBITMQ_HOST 
            value: rabbitmq-service
        resources:
          limits:
            memory: "54Mi"
            cpu: "750m"
